### ISSUE TITLE
DNSSEC support 

### ISSUE THREAD

**Issue by alexandrestein** [albertito/dnss#2]
Hi, 
thank you for this package it is simple and efficient.

Is there any plan to support **DNSSEC**?

**Comment by albertito** [comment]
Hi!  Sorry for not responding before, I didn't realize this was still open :(

dnss passes through queries and is quite agnostic to the record types.

For example, in "dns to https" mode, lookups of DNSSEC-enabled domains work fine, and the record types are passed through to the resolvers fine as well.

Is there anything in specific about DNSSEC that isn't working, or any particular mode you'd like to be supported?

**Comment by alexandrestein** [comment]
Yes, sorry it wasn't clear.

I would like to have DNSSEC validation directly inside the package.

In the meantime I moved to an other solution.
So I don't need it anymore 🥺

Thanks 😊

**Comment by albertito** [comment]
Ah! I see, thanks for clarifying.

No, no plans for DNSSEC validation in the proxy just yet. I would definitely consider patches (provided they don't increase the complexity significantly), but at the moment don't have plans to actively work on it myself.

Thanks!
