### ISSUE TITLE
Custom listening port?

### ISSUE THREAD

**Issue by FallenChromium** [albertito/dnss#3]
Hi! I find this app pretty damn awesome, I don't really want to mess with cloudflared so I used dnss, but the problem is I wanted to use it with Pi-hole, which eats up :53 port, so the problem is I can't launch dnss on this port, it will break things up. I can build my own version, but it will be awesome to be able to control listening port via command args. What do you think?

**Comment by albertito** [comment]
Hi! Thanks for your kind words, I'm glad you like it.

dnss already supports setting the listening ports in the command line, for all the protocols.

If you want to override the :53 you can use the `-dns_listen_addr` flag for that. For example,
`-dns_listen_addr=:9053` should work.

Hopefully this helps but please comment further and reopen if I'm missing something!

Thanks,
        Alberto
