### ISSUE TITLE
Cannot change HTTPS Upstream

### ISSUE THREAD

**Issue by awthwathje** [albertito/dnss#7]
Hi, great software! Just installed `dnss `from the Debian Buster's repo, works good so far!

The only thing which I can't get to work is changing the HTTPS Upstream, even when I enter the CloudFlare's address, seems like the Google service is still used. Care to check if there is a bug?

`Version: 0.0~git20180721.0.2de63ab0-1+b11`

`dnss      1649  0.0  0.1 778316 13504 ?        Ssl  13:15   0:00 /usr/bin/dnss --dns_listen_addr=systemd --monitoring_listen_addr=127.0.0.1:9981 -enable_dns_to_https -https_upstream=https://1.1.1.1/dns-query`

I use https://www.dnsleaktest.com to check which DNS resolvers had been hit.

**Comment by albertito** [comment]
On Fri, Dec 27, 2019 at 04:26:57AM -0800, awthwathje wrote:
>Hi, great package! Just installed `dnss `from the Debian Buster's repo, works good so far!

I'm glad you find it useful :)


>The only thing which I can't get to work is changing the HTTPS Upstream, even when I enter the CloudFlare's address, seems like the Google service is still used. Care to check if there is a bug?
>
>`Version: 0.0~git20180721.0.2de63ab0-1+b11`
>
>`dnss      1649  0.0  0.1 778316 13504 ?        Ssl  13:15   0:00 /usr/bin/dnss --dns_listen_addr=systemd --monitoring_listen_addr=127.0.0.1:9981 -enable_dns_to_https -https_upstream=https://1.1.1.1/dns-query`

Can you look at the dnss logs, especially around start-up, to see what 
they say?

On acursory look I don't see any reason why it shouldn't work.


>I use https://www.dnsleaktest.com to check which DNS resolvers had been hit.

Silly question: are you sure the machine you're running the test from is 
using dnss?

Thanks!

**Comment by awthwathje** [comment]
Hi again. Not sure what it was, but seems like I managed to make it work with the following `ExecStart` directive in the `systemd` service:

`ExecStart=/usr/bin/dnss --dns_listen_addr=systemd --monitoring_listen_addr=127.0.0.1:9981 --enable_dns_to_https --https_upstream=https://1.1.1.1/dsn-query`

Sorry for false positive! I'm closing the issue now.
