### ISSUE TITLE
Is the flag -testing__insecure_http just for testing?

### ISSUE THREAD

**Issue by triatic** [albertito/dnss#8]
Thanks for dnss, very useful!

I use the flag `-testing__insecure_http` because dnss sits behind encrypted Apache, so I do not need dnss to use encryption.

Is the flag `-testing__insecure_http` ok to use in this scenario, i.e. not just for "testing"?

**Comment by albertito** [comment]
Thank you!

Yes, in that scenario it is ok. The only thing the flag does is make dnss listen on http instead of https.

That use case is quite reasonable, so maybe I should rename the flag to just `--insecure_http` or similar. I'll leave this open to track that feature request.

Thanks!

**Comment by triatic** [comment]
Thanks for your reply. Yes, `--insecure_http` or something else without "testing" seems more appropriate as this is a very useful option for reverse proxy usage behind a secure server and not just for testing.

**Comment by albertito** [comment]
Commit 90210b7a8, currently in the `next` branch, implements this.

The flag is renamed to `insecure_http_server`.

I'll move it to the `master` branch in a few days, assuming there are no issues.

Thanks again!

**Comment by albertito** [comment]
Commit 90210b7 is now in `master`, so this should be fixed.

Thanks for reporting this!

**Comment by triatic** [comment]
No problem. I've just downloaded it and I'm using the new flag name. 👍
